##name: Output event details
##on:
##  issues:
##    types: [ opened, edited ]
##jobs:
##  info:
##    runs-on: ubuntu-latest
##    steps:
##      - name: Output GitHub event data
##        run: echo "${{ toJSON(github.event) }}"